name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Generate sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          for file in $(find . -name "*.html" ! -path "./404.html" ! -path "./admin/*"); do
            url="https://mtsprofypisyahda.sch.id${file#.}"
            echo "  <url>" >> sitemap.xml
            echo "    <loc>${url}</loc>" >> sitemap.xml
            echo "    <lastmod>$(date +%Y-%m-%d)</lastmod>" >> sitemap.xml
            echo "    <changefreq>monthly</changefreq>" >> sitemap.xml
            echo "    <priority>0.8</priority>" >> sitemap.xml
            echo "  </url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

      - name: Commit and push sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Auto update sitemap [skip ci]" || echo "No changes to commit"
          git push
